source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Use unicorn as the app server
gem 'unicorn'
gem 'nokogiri', '>= 1.8.1'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'rabbit_feed', path: '../../'

gem 'rails-controller-testing', group: :test
gem 'rspec-rails', group: :test
